export type Airport = {
    iata: string;
    name: string;
    city: string;
    country: string;
};

export const AIRPORTS: Airport[] = [
    // United States
    { iata: "ATL", name: "Hartsfield-Jackson Atlanta International", city: "Atlanta", country: "US" },
    { iata: "LAX", name: "Los Angeles International", city: "Los Angeles", country: "US" },
    { iata: "ORD", name: "O'Hare International", city: "Chicago", country: "US" },
    { iata: "MDW", name: "Chicago Midway International", city: "Chicago", country: "US" },
    { iata: "DFW", name: "Dallas/Fort Worth International", city: "Dallas", country: "US" },
    { iata: "DAL", name: "Dallas Love Field", city: "Dallas", country: "US" },
    { iata: "DEN", name: "Denver International", city: "Denver", country: "US" },
    { iata: "JFK", name: "John F. Kennedy International", city: "New York", country: "US" },
    { iata: "LGA", name: "LaGuardia Airport", city: "New York", country: "US" },
    { iata: "EWR", name: "Newark Liberty International", city: "Newark / New York", country: "US" },
    { iata: "SFO", name: "San Francisco International", city: "San Francisco", country: "US" },
    { iata: "OAK", name: "Oakland International", city: "Oakland", country: "US" },
    { iata: "SJC", name: "Mineta San José International", city: "San Jose", country: "US" },
    { iata: "SEA", name: "Seattle-Tacoma International", city: "Seattle", country: "US" },
    { iata: "MIA", name: "Miami International", city: "Miami", country: "US" },
    { iata: "FLL", name: "Fort Lauderdale-Hollywood International", city: "Fort Lauderdale", country: "US" },
    { iata: "PBI", name: "Palm Beach International", city: "West Palm Beach", country: "US" },
    { iata: "MCO", name: "Orlando International", city: "Orlando", country: "US" },
    { iata: "TPA", name: "Tampa International", city: "Tampa", country: "US" },
    { iata: "RSW", name: "Southwest Florida International", city: "Fort Myers", country: "US" },
    { iata: "JAX", name: "Jacksonville International", city: "Jacksonville", country: "US" },
    { iata: "BOS", name: "Logan International", city: "Boston", country: "US" },
    { iata: "PHL", name: "Philadelphia International", city: "Philadelphia", country: "US" },
    { iata: "DCA", name: "Ronald Reagan Washington National", city: "Washington DC", country: "US" },
    { iata: "IAD", name: "Dulles International", city: "Washington DC", country: "US" },
    { iata: "BWI", name: "Baltimore/Washington International", city: "Baltimore", country: "US" },
    { iata: "IAH", name: "George Bush Intercontinental", city: "Houston", country: "US" },
    { iata: "HOU", name: "William P. Hobby Airport", city: "Houston", country: "US" },
    { iata: "PHX", name: "Phoenix Sky Harbor International", city: "Phoenix", country: "US" },
    { iata: "LAS", name: "Harry Reid International", city: "Las Vegas", country: "US" },
    { iata: "MSP", name: "Minneapolis–Saint Paul International", city: "Minneapolis", country: "US" },
    { iata: "DTW", name: "Detroit Metropolitan Wayne County", city: "Detroit", country: "US" },
    { iata: "CLT", name: "Charlotte Douglas International", city: "Charlotte", country: "US" },
    { iata: "SLC", name: "Salt Lake City International", city: "Salt Lake City", country: "US" },
    { iata: "PDX", name: "Portland International", city: "Portland", country: "US" },
    { iata: "BNA", name: "Nashville International", city: "Nashville", country: "US" },
    { iata: "AUS", name: "Austin-Bergstrom International", city: "Austin", country: "US" },
    { iata: "SAT", name: "San Antonio International", city: "San Antonio", country: "US" },
    { iata: "MSY", name: "Louis Armstrong New Orleans International", city: "New Orleans", country: "US" },
    { iata: "RDU", name: "Raleigh-Durham International", city: "Raleigh-Durham", country: "US" },
    { iata: "SAN", name: "San Diego International", city: "San Diego", country: "US" },
    { iata: "SMF", name: "Sacramento International", city: "Sacramento", country: "US" },
    { iata: "SNA", name: "John Wayne Airport (Orange County)", city: "Santa Ana", country: "US" },
    { iata: "BUR", name: "Hollywood Burbank Airport", city: "Burbank / Los Angeles", country: "US" },
    { iata: "LGB", name: "Long Beach Airport", city: "Long Beach", country: "US" },
    { iata: "STL", name: "St. Louis Lambert International", city: "St. Louis", country: "US" },
    { iata: "MCI", name: "Kansas City International", city: "Kansas City", country: "US" },
    { iata: "MKE", name: "Milwaukee Mitchell International", city: "Milwaukee", country: "US" },
    { iata: "PIT", name: "Pittsburgh International", city: "Pittsburgh", country: "US" },
    { iata: "CLE", name: "Cleveland Hopkins International", city: "Cleveland", country: "US" },
    { iata: "CMH", name: "John Glenn Columbus International", city: "Columbus", country: "US" },
    { iata: "IND", name: "Indianapolis International", city: "Indianapolis", country: "US" },
    { iata: "MSN", name: "Dane County Regional", city: "Madison", country: "US" },
    { iata: "GRR", name: "Gerald R. Ford International", city: "Grand Rapids", country: "US" },
    { iata: "MEM", name: "Memphis International", city: "Memphis", country: "US" },
    { iata: "BHM", name: "Birmingham-Shuttlesworth International", city: "Birmingham", country: "US" },
    { iata: "OKC", name: "Will Rogers World Airport", city: "Oklahoma City", country: "US" },
    { iata: "TUL", name: "Tulsa International", city: "Tulsa", country: "US" },
    { iata: "LIT", name: "Bill and Hillary Clinton National", city: "Little Rock", country: "US" },
    { iata: "ABQ", name: "Albuquerque International Sunport", city: "Albuquerque", country: "US" },
    { iata: "ELP", name: "El Paso International", city: "El Paso", country: "US" },
    { iata: "TUS", name: "Tucson International", city: "Tucson", country: "US" },
    { iata: "HNL", name: "Daniel K. Inouye International", city: "Honolulu", country: "US" },
    { iata: "OGG", name: "Kahului Airport", city: "Maui", country: "US" },
    { iata: "ANC", name: "Ted Stevens Anchorage International", city: "Anchorage", country: "US" },
    { iata: "PVD", name: "T.F. Green Airport", city: "Providence", country: "US" },
    { iata: "BDL", name: "Bradley International", city: "Hartford/Springfield", country: "US" },
    { iata: "ALB", name: "Albany International", city: "Albany", country: "US" },
    { iata: "BUF", name: "Buffalo Niagara International", city: "Buffalo", country: "US" },
    { iata: "SYR", name: "Syracuse Hancock International", city: "Syracuse", country: "US" },
    { iata: "ROC", name: "Frederick Douglass Greater Rochester", city: "Rochester", country: "US" },
    { iata: "ORF", name: "Norfolk International", city: "Norfolk", country: "US" },
    { iata: "RIC", name: "Richmond International", city: "Richmond", country: "US" },
    { iata: "GSP", name: "Greenville-Spartanburg International", city: "Greenville", country: "US" },
    { iata: "CHS", name: "Charleston International", city: "Charleston", country: "US" },
    { iata: "SAV", name: "Savannah/Hilton Head International", city: "Savannah", country: "US" },
    { iata: "PWM", name: "Portland International Jetport", city: "Portland ME", country: "US" },
    { iata: "DSM", name: "Des Moines International", city: "Des Moines", country: "US" },
    { iata: "OMA", name: "Eppley Airfield", city: "Omaha", country: "US" },
    { iata: "ICT", name: "Wichita Dwight D. Eisenhower National", city: "Wichita", country: "US" },

    // Canada
    { iata: "YYZ", name: "Toronto Pearson International", city: "Toronto", country: "CA" },
    { iata: "YYC", name: "Calgary International", city: "Calgary", country: "CA" },
    { iata: "YVR", name: "Vancouver International", city: "Vancouver", country: "CA" },
    { iata: "YUL", name: "Montréal-Trudeau International", city: "Montreal", country: "CA" },
    { iata: "YOW", name: "Ottawa Macdonald-Cartier International", city: "Ottawa", country: "CA" },
    { iata: "YEG", name: "Edmonton International", city: "Edmonton", country: "CA" },
    { iata: "YHZ", name: "Halifax Stanfield International", city: "Halifax", country: "CA" },
    { iata: "YWG", name: "Winnipeg James Armstrong Richardson International", city: "Winnipeg", country: "CA" },

    // United Kingdom
    { iata: "LHR", name: "London Heathrow", city: "London", country: "GB" },
    { iata: "LGW", name: "London Gatwick", city: "London", country: "GB" },
    { iata: "STN", name: "London Stansted", city: "London", country: "GB" },
    { iata: "LTN", name: "London Luton", city: "London", country: "GB" },
    { iata: "LCY", name: "London City Airport", city: "London", country: "GB" },
    { iata: "MAN", name: "Manchester Airport", city: "Manchester", country: "GB" },
    { iata: "BHX", name: "Birmingham Airport", city: "Birmingham", country: "GB" },
    { iata: "EDI", name: "Edinburgh Airport", city: "Edinburgh", country: "GB" },
    { iata: "GLA", name: "Glasgow Airport", city: "Glasgow", country: "GB" },
    { iata: "BRS", name: "Bristol Airport", city: "Bristol", country: "GB" },

    // Europe
    { iata: "CDG", name: "Paris Charles de Gaulle", city: "Paris", country: "FR" },
    { iata: "ORY", name: "Paris Orly", city: "Paris", country: "FR" },
    { iata: "AMS", name: "Amsterdam Schiphol", city: "Amsterdam", country: "NL" },
    { iata: "FRA", name: "Frankfurt Airport", city: "Frankfurt", country: "DE" },
    { iata: "MUC", name: "Munich Airport", city: "Munich", country: "DE" },
    { iata: "BER", name: "Berlin Brandenburg Airport", city: "Berlin", country: "DE" },
    { iata: "HAM", name: "Hamburg Airport", city: "Hamburg", country: "DE" },
    { iata: "DUS", name: "Düsseldorf Airport", city: "Düsseldorf", country: "DE" },
    { iata: "MAD", name: "Adolfo Suárez Madrid–Barajas", city: "Madrid", country: "ES" },
    { iata: "BCN", name: "Barcelona–El Prat", city: "Barcelona", country: "ES" },
    { iata: "FCO", name: "Rome Fiumicino", city: "Rome", country: "IT" },
    { iata: "MXP", name: "Milan Malpensa", city: "Milan", country: "IT" },
    { iata: "LIN", name: "Milan Linate", city: "Milan", country: "IT" },
    { iata: "VCE", name: "Venice Marco Polo", city: "Venice", country: "IT" },
    { iata: "NAP", name: "Naples International", city: "Naples", country: "IT" },
    { iata: "ZRH", name: "Zurich Airport", city: "Zurich", country: "CH" },
    { iata: "GVA", name: "Geneva Airport", city: "Geneva", country: "CH" },
    { iata: "VIE", name: "Vienna International", city: "Vienna", country: "AT" },
    { iata: "BRU", name: "Brussels Airport", city: "Brussels", country: "BE" },
    { iata: "CPH", name: "Copenhagen Airport", city: "Copenhagen", country: "DK" },
    { iata: "ARN", name: "Stockholm Arlanda", city: "Stockholm", country: "SE" },
    { iata: "OSL", name: "Oslo Gardermoen", city: "Oslo", country: "NO" },
    { iata: "HEL", name: "Helsinki-Vantaa", city: "Helsinki", country: "FI" },
    { iata: "LIS", name: "Humberto Delgado Airport (Lisbon)", city: "Lisbon", country: "PT" },
    { iata: "OPO", name: "Francisco Sá Carneiro Airport", city: "Porto", country: "PT" },
    { iata: "ATH", name: "Athens International (Eleftherios Venizelos)", city: "Athens", country: "GR" },
    { iata: "WAW", name: "Warsaw Chopin Airport", city: "Warsaw", country: "PL" },
    { iata: "PRG", name: "Václav Havel Airport Prague", city: "Prague", country: "CZ" },
    { iata: "BUD", name: "Budapest Ferenc Liszt International", city: "Budapest", country: "HU" },
    { iata: "OTP", name: "Henri Coandă International (Bucharest)", city: "Bucharest", country: "RO" },
    { iata: "SOF", name: "Sofia Airport", city: "Sofia", country: "BG" },
    { iata: "ZAG", name: "Franjo Tuđman Airport (Zagreb)", city: "Zagreb", country: "HR" },
    { iata: "DUB", name: "Dublin Airport", city: "Dublin", country: "IE" },
    { iata: "KEF", name: "Keflavík International", city: "Reykjavik", country: "IS" },
    { iata: "HER", name: "Heraklion International", city: "Heraklion / Crete", country: "GR" },
    { iata: "TXL", name: "Berlin Tegel (closed – use BER)", city: "Berlin", country: "DE" },
    { iata: "NCE", name: "Nice Côte d'Azur", city: "Nice", country: "FR" },
    { iata: "LYS", name: "Lyon–Saint-Exupéry", city: "Lyon", country: "FR" },
    { iata: "MRS", name: "Marseille Provence", city: "Marseille", country: "FR" },
    { iata: "TLS", name: "Toulouse-Blagnac", city: "Toulouse", country: "FR" },
    { iata: "SVQ", name: "Seville Airport", city: "Seville", country: "ES" },
    { iata: "AGP", name: "Málaga-Costa del Sol Airport", city: "Málaga", country: "ES" },
    { iata: "PMI", name: "Palma de Mallorca Airport", city: "Palma", country: "ES" },
    { iata: "IBZ", name: "Ibiza Airport", city: "Ibiza", country: "ES" },

    // Middle East
    { iata: "DXB", name: "Dubai International", city: "Dubai", country: "AE" },
    { iata: "AUH", name: "Abu Dhabi International", city: "Abu Dhabi", country: "AE" },
    { iata: "DOH", name: "Hamad International (Doha)", city: "Doha", country: "QA" },
    { iata: "KWI", name: "Kuwait International", city: "Kuwait City", country: "KW" },
    { iata: "BAH", name: "Bahrain International", city: "Manama", country: "BH" },
    { iata: "MCT", name: "Muscat International", city: "Muscat", country: "OM" },
    { iata: "RUH", name: "King Khalid International (Riyadh)", city: "Riyadh", country: "SA" },
    { iata: "JED", name: "King Abdulaziz International (Jeddah)", city: "Jeddah", country: "SA" },
    { iata: "TLV", name: "Ben Gurion International (Tel Aviv)", city: "Tel Aviv", country: "IL" },
    { iata: "AMM", name: "Queen Alia International (Amman)", city: "Amman", country: "JO" },
    { iata: "BEY", name: "Beirut Rafic Hariri International", city: "Beirut", country: "LB" },
    { iata: "CAI", name: "Cairo International", city: "Cairo", country: "EG" },
    { iata: "IST", name: "Istanbul Airport", city: "Istanbul", country: "TR" },
    { iata: "SAW", name: "Istanbul Sabiha Gökçen", city: "Istanbul", country: "TR" },
    { iata: "ESB", name: "Ankara Esenboğa International", city: "Ankara", country: "TR" },

    // Asia – South & Southeast
    { iata: "BOM", name: "Chhatrapati Shivaji Maharaj International (Mumbai)", city: "Mumbai", country: "IN" },
    { iata: "DEL", name: "Indira Gandhi International (Delhi)", city: "New Delhi", country: "IN" },
    { iata: "BLR", name: "Kempegowda International (Bangalore)", city: "Bangalore", country: "IN" },
    { iata: "MAA", name: "Chennai International", city: "Chennai", country: "IN" },
    { iata: "HYD", name: "Rajiv Gandhi International (Hyderabad)", city: "Hyderabad", country: "IN" },
    { iata: "CCU", name: "Netaji Subhas Chandra Bose International (Kolkata)", city: "Kolkata", country: "IN" },
    { iata: "COK", name: "Cochin International", city: "Kochi", country: "IN" },
    { iata: "CMB", name: "Bandaranaike International (Colombo)", city: "Colombo", country: "LK" },
    { iata: "DAC", name: "Hazrat Shahjalal International (Dhaka)", city: "Dhaka", country: "BD" },
    { iata: "KTM", name: "Tribhuvan International (Kathmandu)", city: "Kathmandu", country: "NP" },
    { iata: "SIN", name: "Singapore Changi", city: "Singapore", country: "SG" },
    { iata: "KUL", name: "Kuala Lumpur International", city: "Kuala Lumpur", country: "MY" },
    { iata: "BKK", name: "Suvarnabhumi Airport (Bangkok)", city: "Bangkok", country: "TH" },
    { iata: "DMK", name: "Don Mueang International (Bangkok)", city: "Bangkok", country: "TH" },
    { iata: "CGK", name: "Soekarno-Hatta International (Jakarta)", city: "Jakarta", country: "ID" },
    { iata: "DPS", name: "Ngurah Rai International (Bali)", city: "Bali / Denpasar", country: "ID" },
    { iata: "MNL", name: "Ninoy Aquino International (Manila)", city: "Manila", country: "PH" },
    { iata: "CEB", name: "Mactan-Cebu International", city: "Cebu", country: "PH" },
    { iata: "SGN", name: "Tan Son Nhat International (Ho Chi Minh)", city: "Ho Chi Minh City", country: "VN" },
    { iata: "HAN", name: "Noi Bai International (Hanoi)", city: "Hanoi", country: "VN" },
    { iata: "DAD", name: "Da Nang International", city: "Da Nang", country: "VN" },
    { iata: "PNH", name: "Phnom Penh International", city: "Phnom Penh", country: "KH" },
    { iata: "RGN", name: "Yangon International", city: "Yangon", country: "MM" },
    { iata: "REP", name: "Siem Reap International", city: "Siem Reap", country: "KH" },

    // Asia – East
    { iata: "HKG", name: "Hong Kong International", city: "Hong Kong", country: "HK" },
    { iata: "PEK", name: "Beijing Capital International", city: "Beijing", country: "CN" },
    { iata: "PKX", name: "Beijing Daxing International", city: "Beijing", country: "CN" },
    { iata: "PVG", name: "Shanghai Pudong International", city: "Shanghai", country: "CN" },
    { iata: "SHA", name: "Shanghai Hongqiao International", city: "Shanghai", country: "CN" },
    { iata: "CAN", name: "Guangzhou Baiyun International", city: "Guangzhou", country: "CN" },
    { iata: "CTU", name: "Chengdu Tianfu International", city: "Chengdu", country: "CN" },
    { iata: "SZX", name: "Shenzhen Bao'an International", city: "Shenzhen", country: "CN" },
    { iata: "XIY", name: "Xi'an Xianyang International", city: "Xi'an", country: "CN" },
    { iata: "KMG", name: "Kunming Changshui International", city: "Kunming", country: "CN" },
    { iata: "HGH", name: "Hangzhou Xiaoshan International", city: "Hangzhou", country: "CN" },
    { iata: "NKG", name: "Nanjing Lukou International", city: "Nanjing", country: "CN" },
    { iata: "CKG", name: "Chongqing Jiangbei International", city: "Chongqing", country: "CN" },
    { iata: "TPE", name: "Taiwan Taoyuan International", city: "Taipei", country: "TW" },
    { iata: "TSA", name: "Taipei Songshan Airport", city: "Taipei", country: "TW" },
    { iata: "ICN", name: "Incheon International (Seoul)", city: "Seoul", country: "KR" },
    { iata: "GMP", name: "Seoul Gimpo International", city: "Seoul", country: "KR" },
    { iata: "PUS", name: "Gimhae International (Busan)", city: "Busan", country: "KR" },
    { iata: "NRT", name: "Tokyo Narita International", city: "Tokyo", country: "JP" },
    { iata: "HND", name: "Tokyo Haneda International", city: "Tokyo", country: "JP" },
    { iata: "KIX", name: "Kansai International (Osaka)", city: "Osaka", country: "JP" },
    { iata: "ITM", name: "Osaka Itami Airport", city: "Osaka", country: "JP" },
    { iata: "NGO", name: "Chubu Centrair International (Nagoya)", city: "Nagoya", country: "JP" },
    { iata: "CTS", name: "New Chitose Airport (Sapporo)", city: "Sapporo", country: "JP" },
    { iata: "FUK", name: "Fukuoka Airport", city: "Fukuoka", country: "JP" },

    // Oceania
    { iata: "SYD", name: "Sydney Kingsford Smith", city: "Sydney", country: "AU" },
    { iata: "MEL", name: "Melbourne Airport (Tullamarine)", city: "Melbourne", country: "AU" },
    { iata: "BNE", name: "Brisbane Airport", city: "Brisbane", country: "AU" },
    { iata: "PER", name: "Perth Airport", city: "Perth", country: "AU" },
    { iata: "ADL", name: "Adelaide Airport", city: "Adelaide", country: "AU" },
    { iata: "CBR", name: "Canberra Airport", city: "Canberra", country: "AU" },
    { iata: "AKL", name: "Auckland Airport", city: "Auckland", country: "NZ" },
    { iata: "WLG", name: "Wellington Airport", city: "Wellington", country: "NZ" },
    { iata: "CHC", name: "Christchurch Airport", city: "Christchurch", country: "NZ" },

    // Africa
    { iata: "JNB", name: "O.R. Tambo International (Johannesburg)", city: "Johannesburg", country: "ZA" },
    { iata: "CPT", name: "Cape Town International", city: "Cape Town", country: "ZA" },
    { iata: "NBO", name: "Jomo Kenyatta International (Nairobi)", city: "Nairobi", country: "KE" },
    { iata: "ADD", name: "Addis Ababa Bole International", city: "Addis Ababa", country: "ET" },
    { iata: "LOS", name: "Murtala Muhammed International (Lagos)", city: "Lagos", country: "NG" },
    { iata: "ABV", name: "Nnamdi Azikiwe International (Abuja)", city: "Abuja", country: "NG" },
    { iata: "ACC", name: "Kotoka International (Accra)", city: "Accra", country: "GH" },
    { iata: "DKR", name: "Blaise Diagne International (Dakar)", city: "Dakar", country: "SN" },
    { iata: "CMN", name: "Mohammed V International (Casablanca)", city: "Casablanca", country: "MA" },
    { iata: "TUN", name: "Tunis-Carthage International", city: "Tunis", country: "TN" },
    { iata: "ALG", name: "Houari Boumediene Airport (Algiers)", city: "Algiers", country: "DZ" },
    { iata: "DAR", name: "Julius Nyerere International (Dar es Salaam)", city: "Dar es Salaam", country: "TZ" },

    // Latin America
    { iata: "GRU", name: "São Paulo–Guarulhos International", city: "São Paulo", country: "BR" },
    { iata: "CGH", name: "São Paulo Congonhas Airport", city: "São Paulo", country: "BR" },
    { iata: "GIG", name: "Rio de Janeiro–Galeão International", city: "Rio de Janeiro", country: "BR" },
    { iata: "SDU", name: "Rio de Janeiro Santos Dumont", city: "Rio de Janeiro", country: "BR" },
    { iata: "BSB", name: "Brasília International", city: "Brasília", country: "BR" },
    { iata: "FOR", name: "Pinto Martins – Fortaleza International", city: "Fortaleza", country: "BR" },
    { iata: "EZE", name: "Ministro Pistarini International (Buenos Aires)", city: "Buenos Aires", country: "AR" },
    { iata: "AEP", name: "Jorge Newbery Airfield (Buenos Aires)", city: "Buenos Aires", country: "AR" },
    { iata: "SCL", name: "Arturo Merino Benítez International (Santiago)", city: "Santiago", country: "CL" },
    { iata: "LIM", name: "Jorge Chávez International (Lima)", city: "Lima", country: "PE" },
    { iata: "BOG", name: "El Dorado International (Bogotá)", city: "Bogotá", country: "CO" },
    { iata: "MDE", name: "José María Córdova International (Medellín)", city: "Medellín", country: "CO" },
    { iata: "UIO", name: "Mariscal Sucre International (Quito)", city: "Quito", country: "EC" },
    { iata: "GYE", name: "José Joaquín de Olmedo International (Guayaquil)", city: "Guayaquil", country: "EC" },
    { iata: "CCS", name: "Simón Bolívar International (Caracas)", city: "Caracas", country: "VE" },
    { iata: "PTY", name: "Tocumen International (Panama City)", city: "Panama City", country: "PA" },
    { iata: "MEX", name: "Mexico City International (Benito Juárez)", city: "Mexico City", country: "MX" },
    { iata: "CUN", name: "Cancún International", city: "Cancún", country: "MX" },
    { iata: "GDL", name: "Miguel Hidalgo y Costilla International (Guadalajara)", city: "Guadalajara", country: "MX" },
    { iata: "MTY", name: "General Mariano Escobedo International (Monterrey)", city: "Monterrey", country: "MX" },
    { iata: "SJO", name: "Juan Santamaría International (San José)", city: "San José", country: "CR" },
    { iata: "MBJ", name: "Sangster International (Montego Bay)", city: "Montego Bay", country: "JM" },
    { iata: "HAV", name: "José Martí International (Havana)", city: "Havana", country: "CU" },
    { iata: "NAS", name: "Lynden Pindling International (Nassau)", city: "Nassau", country: "BS" },

    // Central Asia & South Asia extras
    { iata: "KHI", name: "Jinnah International (Karachi)", city: "Karachi", country: "PK" },
    { iata: "LHE", name: "Allama Iqbal International (Lahore)", city: "Lahore", country: "PK" },
    { iata: "ISB", name: "Islamabad International", city: "Islamabad", country: "PK" },
    { iata: "KBL", name: "Hamid Karzai International (Kabul)", city: "Kabul", country: "AF" },
    { iata: "TAS", name: "Tashkent International", city: "Tashkent", country: "UZ" },
    { iata: "ALA", name: "Almaty International", city: "Almaty", country: "KZ" },
    { iata: "NQZ", name: "Nursultan Nazarbayev International (Astana)", city: "Astana", country: "KZ" },

    // Russia & Eastern Europe
    { iata: "SVO", name: "Sheremetyevo International (Moscow)", city: "Moscow", country: "RU" },
    { iata: "DME", name: "Domodedovo International (Moscow)", city: "Moscow", country: "RU" },
    { iata: "LED", name: "Pulkovo Airport (St. Petersburg)", city: "St. Petersburg", country: "RU" },
    { iata: "KBP", name: "Boryspil International (Kyiv)", city: "Kyiv", country: "UA" },
    { iata: "RIX", name: "Riga International", city: "Riga", country: "LV" },
    { iata: "TLL", name: "Lennart Meri Tallinn Airport", city: "Tallinn", country: "EE" },
    { iata: "VNO", name: "Vilnius Airport", city: "Vilnius", country: "LT" },
    { iata: "SKG", name: "Thessaloniki Macedonia International", city: "Thessaloniki", country: "GR" },
    { iata: "BEG", name: "Belgrade Nikola Tesla Airport", city: "Belgrade", country: "RS" },
];
